import Resources from './resources';

const prefixEndpoint = Resources.api;
const PREFIX_SCHOOL_ADMIN = 'SchoolAdmin';
const PREFIX_CLASS_ENROLLMENT = 'ClassEnrollment';
const PREFIX_SCHOOL_SUBSCRIPTION = 'SchoolSubscriptions';
const PREFIX_INVOICE = 'InvoiceManager';
const PREFIX_SCHOOL_INVOICE = 'Invoices';
const PREFIX_SUBSCRIPTION_PLAN = 'SubscriptionPlan';
const PREFIX_BUS_ROUTE = 'BusRoute';
const PREFIX_SERVICE_PACKAGE = 'ServicePackage';
const PREFIX_SCHOOL_YEAR = 'SchoolYear';
const PREFIX_DASHBOARD = 'Dashboard';
const PREFIX_SUBJECT_SCHOOL = 'Subject';
const PREFIX_BUS_SUPERVISOR = 'BusSupervisor';
const PREFIX_TEACHER = 'Teachers';
const PREFIX_PUPIL = 'Pupils';
const PREFIX_BUS_STOP = 'BusStop';
const PREFIX_BUS = 'Bus';
const PREFIX_BUS_ENROLLMENT = 'BusEnrollment';
const PREFIX_TIME_SLOT = 'TimeSlot';
const PREFIX_CLUB = 'Club';
const PREFIX_CLUB_ENROLLMENT = 'ClubEnrollment';
export const END_POINT = {
  AUTH: {
    LOGIN: 'auth/login',
    REGISTER: 'auth/register-school-admin',
    VERIFY_EMAIL: 'auth/verify-email',
    FORGOT_PASSWORD: 'auth/forgot-password',
    CONFIRM_CODE_RESET_PASSWORD: 'auth/confirm-code-reset',
    RESET_PASSWORD: 'auth/reset-password',
    LOGOUT: 'auth/logout',
    VERIFY_FIRST_LOGIN: 'auth/verify-first-login',
    CONFIRM_VERIFY_FIRST_LOGIN: 'auth/confirm-code-first-login',
  },
  DASHBOARD: {
    INDEX: '/home-view',
  },
  CLASS: {
    DETAIL: 'class/get-class-detail',
    ASSIGNED_CLASS: 'class/get-assigned-classes',
    ADD: 'Class/add-classes',
    DELETE: 'Class/delete-class',
    GET_CLASS: 'Class/get-list-class',
    GET_ENROLLED_CLASS: 'Class/get-enrollment-class',
    GET_PUPIL_CLASS: 'Class/get-classes-of-pupil',
    GET_PUPIL_CLASS_DETAIL: 'Class/get-pupil-class',
    DETAIL_FOR_SCHOOL_ADMIN: 'Class/get-class-detail-for-school-admin',
    UPDATE: 'Class/update-class',
  },
  TIME_SLOT: {
    ALL: 'timeslot/get-all-timeslot',
    GET: 'get-all-timeslots',
    CREATE: 'create-timeslot',
    DETAIL: 'get-timeslot-detail',
    UPDATE: 'update-timeslot',
    DELETE: 'delete-timeslot',
  },
  SUBJECT: {
    ALL: 'subject/get-all-subject',
    CREATE: 'create-subject',
    EDIT: 'update-subject',
    DELETE: 'delete-subject',
  },
  TIMETABLE: {
    GET: 'timetable/get-timetable-detail',
    CREATE: 'timetable/create-timetable',
    UPDATE: 'timetable/update-timetable',
    DELETE: 'timetable/delete-timetable',
  },
  SEMESTER: {
    GET: 'semester/get-all-semester',
    GET_CURRENT: 'semester/get-current-semester',
    GET_NEXT: 'semester/get-next-semester',
    INDEX: 'semester/get-semesters-by-schoolyearid',
    DETAIL: 'semester/detail-semester',
    CREATE: 'semester/create-semester',
    EDIT: 'semester/update-semester',
    DELETE: 'semester/delete-semester',
  },
  TEACHER: {
    ALL: 'get-all',
    CREATE: 'create',
    DETAIL: 'get-detail',
    UPDATE: 'update',
    GET_ASSIGN: 'Teacher/get-teacher-assign',
    PROFILE: 'Teacher',
    DELETE: 'delete-multiple-teachers',
    IMPORT_EXCEL: 'import-teachers'
  },
  PUPIL: {
    ALL: 'get-all',
    CREATE: 'create',
    DETAIL: 'get-detail',
    UPDATE: 'update',
    GET_ASSIGN: 'Pupil/get-pupil-assign',
    PROFILE: 'Pupil',
    DELETE: 'delete-multiple-pupils',
    IMPORT_EXCEL: 'import-pupils'
  },
  SCHOOL_SUBSCRIPTION: {
    ALL: 'all',
    CURRENT: 'current',
    CREATE_INVOICE: 'create-invoice',
    GENERATE_PAYMENT: 'generate-payment-url',
    PAYMENT_CALLBACK: 'payment-callback',
  },
  SCHOOL_ADMIN: {
    INDEX: 'all-account-school-admin',
    DETAIL: 'detail-account-school-admin',
    CREATE: 'create-account-school-admin',
    EDIT: 'update-account-school-admin',
    DELETE: 'delete-account-school-admin',
  },
  NOTIFICATION: {
    LIST: 'notification',
    DETAIL: 'notification/detail',
    CATEGORIES: 'notification/categories',
    CREATE: 'notification',
    UPDATE: 'notification',
    DELETE: 'notification',
  },
  SCHOOL: {
    GET_INFO: 'School/get-info-school',
    UPDATE: 'School/update-info-school',
    DASHBOARD: 'School/get-school-dashboard',
    CHANGE_PASSWORD: 'School/change-password',
  },
  CLASS_ENROLLMENT: {
    ASSIGN_TEACHER: 'assign-teacher',
    ASSIGN_PUPIL: 'assign-pupil',
    REMOVE_TEACHER: 'remove-teacher',
    GET_TEACHER_ID: 'get-teacher-by-classId-semesterId',
    UPDATE_ASSIGN_TEACHER: 'update-assign-teacher',
    GET_TEACHER_SWAP: 'get-teacher-in-class',
    SWAP_TEACHER: 'swap-teacher-in-class',
    GET_MEMBER_IN_CLASS: 'get-member-in-class-enrollment',
    REMOVE_MEMBER: 'remove-member',
    GET_MEMBER_IN_NEXT_SEMESTER: 'get-member-to-copy',
    PUPILS_TO_GRADUATE: 'pupils-to-graduate'
  },
  CLUB: {
    DETAIL: 'club/get-current-club-detail',
    ASSIGNED_CLUB: 'club/get-assign-club',
    ENROLLED_CLUB: 'club/get-enrolled-club',
    GET_BY_SEMESTER_ACTIVE: 'club/get-clubs-by-school-id',
    GET_ALL: 'get-all-clubs',
    MAIN_DETAIL: 'get-club-detail',
    CREATE: 'create-club',
    UPDATE: 'update-club',
    DELETE: 'delete-club',
  },
  INVOICE_MANAGER: {
    INDEX: 'all-invoice',
    DETAIL: 'get-invoice',
    CREATE: 'create-invoice',
    EDIT: 'update-invoice',
    DELETE: 'delete-multiple-invoices',
    SCHEDULE: 'schedule-invoice',
  },
  CLASS_APPLICATION: {
    GET_LIST: 'ClassApplication/get-class-application',
    CATEGORY: 'ClassApplication/get-class-application-category',
    RESPONSE: 'ClassApplication/response-class-application',
    GET_LIST_BY_PUPIL: 'ClassApplication/get-pupil-application',
    CREATE: 'ClassApplication/create-class-application',
    UPDATE: 'ClassApplication/update-class-application',
    DELETE: 'ClassApplication/delete-class-application',
  },
  ATTENDANCE: {
    PREPARE: 'attendance/prepare-attendance-record',
    CREATE: 'attendance/create-attendance-record',
    GET: 'attendance/get-attendance-record',
    UPDATE: 'attendance/update-attendance-record',
    LIST: 'attendance/get-attendance-list',
    PUPIL_ATTENDANCE: 'attendance/get-pupil-attendance-list',
  },
  BUS: {
    ASSIGNED_BUS: 'bus/get-assigned-bus',
    ENROLLMENT_BUS: 'bus/get-enrollment-bus',
    DETAIL_BUS: 'bus/get-bus-detail',
    PUPIL_ENROLLMENT: 'bus/get-list-bus-of-pupil',
    PUPIL_BUS_DETAIL: 'bus/get-bus-detail-of-pupil',
    INDEX: 'get-all-bus',
    INFORMATION: 'get-bus-for-admin-school',
    CREATE: 'create-bus',
    UPDATE: 'update-bus',
    DELETE: 'delete-bus',
  },
  SUBSCRIPTION: {
    ALL: 'get-subscription',
    DETAIL: 'get-subscription',
  },
  INVOICE: {
    ALL: 'get-all',
    DETAIL: 'get-invoice',
    DELETE: 'delete-multiple-invoices',
    GET_BY_SUBSCRIPTION: 'get-newest-invoice',
  },
  CLUB_ENROLLMENT: {
    PUPIL_CREATE: 'ClubEnrollment/pupil-create-club-enrollment',
    UPDATE: 'ClubEnrollment/update-club-enrollment',
    GET_BY_PUPIL_ID: 'ClubEnrollment/get-club-enrollment-by-pupil-id',
    GET_BY_SEMESTER: 'get-club-enrollment-by-semesterId',
    CREATE: 'assign-member-to-club',
    UPDATE_INFO: 'update-member-in-club',
    REMOVE: 'remove-member-in-club',
    GET_TEACHER_NOT_IN_CLUB: 'get-teachers-not-in-club',
    GET_PUPIL_NOT_IN_CLUB: 'get-pupils-not-in-club',
    GET_PUPIL_REGISTER_CLUB: 'get-pupils-register-club',
    GET_MEMBER_TO_COPY: 'get-member-to-copy-club'
  },
  BUS_ROUTE: {
    INDEX: 'get-bus-route',
    ADD: 'create-bus-route',
    UPDATE: 'update-bus-route',
    DETAIL: 'detail-bus-route',
    DELETE: 'delete-bus-route',
  },
  BUS_STOP: {
    INDEX: 'get-all-bus-stops',
    DETAIL: 'get-bus-stop-detail',
    CREATE: 'create-bus-stop',
    UPDATE: 'update-bus-stop',
    DELETE: 'delete-bus-stop',
  },
  BUS_ENROLLMENT: {
    INDEX: 'get-all-enrollments',
    DETAIL: 'get-enrollment-detail',
    CREATE: 'create-bus-enrollment',
    UPDATE: 'update-enrollment',
    DELETE: 'delete-enrollment',
    GET_PUPILS_WITHOUT_BUS:'get-pupil-without-in-bus',
    GET_BUS_SUPERVISOR_WITHOUT_BUS:'get-bus-supervisor-without-in-bus',
    GET_PUPILS_IN_BUS_STOP:'get-list-pupils-in-bus-stop',
  },
  SCORE: {
    CLASS_SCORE_LIST: 'PupilScore/get-class-score',
    GET_PUPIL_FOR_CREATE: 'PupilScore/get-pupil-for-create',
    CREATE: 'PupilScore/create-pupil-scores',
    UPDATE: 'PupilScore/update-pupil-scores',
    GET_PUPIL_SCORE: 'PupilScore/get-pupil-scores',
    GET_INDIVIDUAL_SCORE: 'PupilScore/get-individual-pupil-scores',
  },
  SERVICE_PACKAGE: {
    INDEX: 'get-all-service-package',
    DETAIL: 'get-service-package-by-id',
    UPDATE: 'update-service-package',
    CREATE: 'create-service-package',
  },
  SCHOOL_YEAR: {
    INDEX: 'get-schoolyear-by-schoolid',
    DETAIL: 'detail-schoolyear',
    CREATE: 'create-schoolyear',
    EDIT: 'update-schoolyear',
    DELETE: 'delete-schoolyear',
  },
  FEEDBACK: {
    CLASS_FEEDBACKS: 'PupilFeedback/get-list-class-feedback',
    CREATE_FEEDBACK: 'PupilFeedback/create-pupil-feedback',
    UPDATE_FEEDBACK: 'PupilFeedback/update-pupil-feedback',
    DELETE_FEEDBACK: 'PupilFeedback/delete-pupil-feedback',
    GET_PUPIL_FEEDBACK: 'PupilFeedback/get-pupil-feedback',
  },
  DASHBOARD_ADMIN: {
    INDEX: 'get-revenue',
    TOTAL_SCHOOL: 'get-total-school',
    TOTAL_SCHOOL_SUBSCRIPTION: 'get-total-subscription',
  },
  BUS_SUPERVISOR: {
    GET: 'get-bus-supervisor-detail',
    UPDATE: 'update-bus-supervisor',
    CREATE:'create',
    UPDATE_ACCOUNT: 'update',
    ALL: 'get-all',
    DETAIL: 'get-detail',
    DELETE: 'delete-multiple-busSupervisors',
    IMPORT_EXCEL: 'import-busSupervisors'
  },
};

export const API_URL = {
  AUTH: {
    LOGIN: `${prefixEndpoint}/${END_POINT.AUTH.LOGIN}`,
    REGISTER: `${prefixEndpoint}/${END_POINT.AUTH.REGISTER}`,
    VERIFY_EMAIL: `${prefixEndpoint}/${END_POINT.AUTH.VERIFY_EMAIL}`,
    FORGOT_PASSWORD: `${prefixEndpoint}/${END_POINT.AUTH.FORGOT_PASSWORD}`,
    CONFIRM_CODE_RESET_PASSWORD: `${prefixEndpoint}/${END_POINT.AUTH.CONFIRM_CODE_RESET_PASSWORD}`,
    RESET_PASSWORD: `${prefixEndpoint}/${END_POINT.AUTH.RESET_PASSWORD}`,
    LOGOUT: `${prefixEndpoint}/${END_POINT.AUTH.LOGOUT}`,
    VERIFY_FIRST_LOGIN: `${prefixEndpoint}/${END_POINT.AUTH.VERIFY_FIRST_LOGIN}`,
    CONFIRM_VERIFY_FIRST_LOGIN: `${prefixEndpoint}/${END_POINT.AUTH.CONFIRM_VERIFY_FIRST_LOGIN}`,
  },
  CLASS: {
    DETAIL: `${prefixEndpoint}/${END_POINT.CLASS.DETAIL}`,
    ASSIGNED_CLASS: `${prefixEndpoint}/${END_POINT.CLASS.ASSIGNED_CLASS}`,
    ADD: `${prefixEndpoint}/${END_POINT.CLASS.ADD}`,
    DELETE: `${prefixEndpoint}/${END_POINT.CLASS.DELETE}`,
    GET_CLASS: `${prefixEndpoint}/${END_POINT.CLASS.GET_CLASS}`,
    GET_ENROLLED_CLASS: `${prefixEndpoint}/${END_POINT.CLASS.GET_ENROLLED_CLASS}`,
    GET_PUPIL_CLASS: `${prefixEndpoint}/${END_POINT.CLASS.GET_PUPIL_CLASS}`,
    GET_PUPIL_CLASS_DETAIL: `${prefixEndpoint}/${END_POINT.CLASS.GET_PUPIL_CLASS_DETAIL}`,
    UPDATE: `${prefixEndpoint}/${END_POINT.CLASS.UPDATE}`,
    DETAIL_FOR_SCHOOL_ADMIN: `${prefixEndpoint}/${END_POINT.CLASS.DETAIL_FOR_SCHOOL_ADMIN}`,
  },
  TIME_SLOT: {
    ALL: `${prefixEndpoint}/${END_POINT.TIME_SLOT.ALL}`,
    GET: `${prefixEndpoint}/${PREFIX_TIME_SLOT}/${END_POINT.TIME_SLOT.GET}`,
    CREATE: `${prefixEndpoint}/${PREFIX_TIME_SLOT}/${END_POINT.TIME_SLOT.CREATE}`,
    DETAIL: `${prefixEndpoint}/${PREFIX_TIME_SLOT}/${END_POINT.TIME_SLOT.DETAIL}`,
    UPDATE: `${prefixEndpoint}/${PREFIX_TIME_SLOT}/${END_POINT.TIME_SLOT.UPDATE}`,
    DELETE: `${prefixEndpoint}/${PREFIX_TIME_SLOT}/${END_POINT.TIME_SLOT.DELETE}`,
  },
  TIMETABLE: {
    GET: `${prefixEndpoint}/${END_POINT.TIMETABLE.GET}`,
    CREATE: `${prefixEndpoint}/${END_POINT.TIMETABLE.CREATE}`,
    UPDATE: `${prefixEndpoint}/${END_POINT.TIMETABLE.UPDATE}`,
    DELETE: `${prefixEndpoint}/${END_POINT.TIMETABLE.DELETE}`,
  },
  SUBJECT: {
    ALL: `${prefixEndpoint}/${END_POINT.SUBJECT.ALL}`,
    CREATE: `${prefixEndpoint}/${PREFIX_SUBJECT_SCHOOL}/${END_POINT.SUBJECT.CREATE}`,
    EDIT: (id: number) => `${prefixEndpoint}/${PREFIX_SUBJECT_SCHOOL}/${END_POINT.SUBJECT.EDIT}/${id}`,
    DELETE: (id: number) => `${prefixEndpoint}/${PREFIX_SUBJECT_SCHOOL}/${END_POINT.SUBJECT.DELETE}/${id}`,
  },
  SEMESTER: {
    GET: `${prefixEndpoint}/${END_POINT.SEMESTER.GET}`,
    GET_CURRENT: `${prefixEndpoint}/${END_POINT.SEMESTER.GET_CURRENT}`,
    GET_NEXT: `${prefixEndpoint}/${END_POINT.SEMESTER.GET_NEXT}`,
    INDEX: (schoolYearId: number) => `${prefixEndpoint}/${END_POINT.SEMESTER.INDEX}?schoolYearId=${schoolYearId}`,
    DETAIL: (id: number) => `${prefixEndpoint}/${END_POINT.SEMESTER.DETAIL}/${id}`,
    CREATE: `${prefixEndpoint}/${END_POINT.SEMESTER.CREATE}`,
    EDIT: `${prefixEndpoint}/${END_POINT.SEMESTER.EDIT}`,
    DELETE: (id: number) => `${prefixEndpoint}/${END_POINT.SEMESTER.DELETE}/${id}`,
  },
  TEACHER: {
    ALL: `${prefixEndpoint}/${PREFIX_TEACHER}/${END_POINT.TEACHER.ALL}`,
    CREATE: `${prefixEndpoint}/${PREFIX_TEACHER}/${END_POINT.TEACHER.CREATE}`,
    DETAIL: `${prefixEndpoint}/${PREFIX_TEACHER}/${END_POINT.TEACHER.DETAIL}`,
    UPDATE: `${prefixEndpoint}/${PREFIX_TEACHER}/${END_POINT.TEACHER.UPDATE}`,
    GET_ASSIGN: `${prefixEndpoint}/${END_POINT.TEACHER.GET_ASSIGN}`,
    PROFILE: `${prefixEndpoint}/${END_POINT.TEACHER.PROFILE}`,
    DELETE: `${prefixEndpoint}/${PREFIX_TEACHER}/${END_POINT.TEACHER.DELETE}`,
    IMPORT_EXCEL: `${prefixEndpoint}/${PREFIX_TEACHER}/${END_POINT.TEACHER.IMPORT_EXCEL}`,
  },
  PUPIL: {
    ALL: `${prefixEndpoint}/${PREFIX_PUPIL}/${END_POINT.PUPIL.ALL}`,
    CREATE: `${prefixEndpoint}/${PREFIX_PUPIL}/${END_POINT.PUPIL.CREATE}`,
    DETAIL: `${prefixEndpoint}/${PREFIX_PUPIL}/${END_POINT.PUPIL.DETAIL}`,
    UPDATE: `${prefixEndpoint}/${PREFIX_PUPIL}/${END_POINT.PUPIL.UPDATE}`,
    GET_ASSIGN: `${prefixEndpoint}/${END_POINT.PUPIL.GET_ASSIGN}`,
    PROFILE: `${prefixEndpoint}/${END_POINT.PUPIL.PROFILE}`,
    DELETE: `${prefixEndpoint}/${PREFIX_PUPIL}/${END_POINT.PUPIL.DELETE}`,
    IMPORT_EXCEL: `${prefixEndpoint}/${PREFIX_PUPIL}/${END_POINT.PUPIL.IMPORT_EXCEL}`,
  },
  SCHOOL_SUBSCRIPTION: {
    ALL: `${prefixEndpoint}/${PREFIX_SCHOOL_SUBSCRIPTION}/${END_POINT.SCHOOL_SUBSCRIPTION.ALL}`,
    CURRENT: `${prefixEndpoint}/${PREFIX_SCHOOL_SUBSCRIPTION}/${END_POINT.SCHOOL_SUBSCRIPTION.CURRENT}`,
    CREATE_INVOICE: `${prefixEndpoint}/${PREFIX_SCHOOL_SUBSCRIPTION}/${END_POINT.SCHOOL_SUBSCRIPTION.CREATE_INVOICE}`,
    GENERATE_PAYMENT: `${prefixEndpoint}/${PREFIX_SCHOOL_SUBSCRIPTION}/${END_POINT.SCHOOL_SUBSCRIPTION.GENERATE_PAYMENT}`,
    PAYMENT_CALLBACK: `${prefixEndpoint}/${PREFIX_SCHOOL_SUBSCRIPTION}/${END_POINT.SCHOOL_SUBSCRIPTION.PAYMENT_CALLBACK}`,
  },
  SCHOOL_ADMIN: {
    INDEX: `${prefixEndpoint}/${PREFIX_SCHOOL_ADMIN}/${END_POINT.SCHOOL_ADMIN.INDEX}`,
    DETAIL: (id: number) => `${prefixEndpoint}/${PREFIX_SCHOOL_ADMIN}/${id}/${END_POINT.SCHOOL_ADMIN.DETAIL}`,
    CREATE: `${prefixEndpoint}/${PREFIX_SCHOOL_ADMIN}/${END_POINT.SCHOOL_ADMIN.CREATE}`,
    EDIT: (id: number) => `${prefixEndpoint}/${PREFIX_SCHOOL_ADMIN}/${id}/${END_POINT.SCHOOL_ADMIN.EDIT}`,
    DELETE: (id: number) => `${prefixEndpoint}/${PREFIX_SCHOOL_ADMIN}/${id}/${END_POINT.SCHOOL_ADMIN.DELETE}`,
  },
  NOTIFICATION: {
    LIST: `${prefixEndpoint}/${END_POINT.NOTIFICATION.LIST}`,
    DETAIL: `${prefixEndpoint}/${END_POINT.NOTIFICATION.DETAIL}`,
    CATEGORIES: `${prefixEndpoint}/${END_POINT.NOTIFICATION.CATEGORIES}`,
    CREATE: `${prefixEndpoint}/${END_POINT.NOTIFICATION.CREATE}`,
    UPDATE: `${prefixEndpoint}/${END_POINT.NOTIFICATION.UPDATE}`,
    DELETE: `${prefixEndpoint}/${END_POINT.NOTIFICATION.DELETE}`,
  },
  SCHOOL: {
    GET_INFO: `${prefixEndpoint}/${END_POINT.SCHOOL.GET_INFO}`,
    UPDATE: `${prefixEndpoint}/${END_POINT.SCHOOL.UPDATE}`,
    DASHBOARD: `${prefixEndpoint}/${END_POINT.SCHOOL.DASHBOARD}`,
    CHANGE_PASSWORD: `${prefixEndpoint}/${END_POINT.SCHOOL.CHANGE_PASSWORD}`,
  },
  CLASS_ENROLLMENT: {
    ASSIGN_TEACHER: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.ASSIGN_TEACHER}`,
    ASSIGN_PUPIL: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.ASSIGN_PUPIL}`,
    REMOVE_TEACHER: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.REMOVE_TEACHER}`,
    GET_TEACHER_ID: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.GET_TEACHER_ID}`,
    UPDATE_ASSIGN_TEACHER: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.UPDATE_ASSIGN_TEACHER}`,
    GET_TEACHER_SWAP: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.GET_TEACHER_SWAP}`,
    SWAP_TEACHER: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.SWAP_TEACHER}`,
    GET_MEMBER_IN_CLASS: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.GET_MEMBER_IN_CLASS}`,
    REMOVE_MEMBER: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.REMOVE_MEMBER}`,
    GET_MEMBER_IN_NEXT_SEMESTER: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.GET_MEMBER_IN_NEXT_SEMESTER}`,
    PUPILS_TO_GRADUATE: `${prefixEndpoint}/${PREFIX_CLASS_ENROLLMENT}/${END_POINT.CLASS_ENROLLMENT.PUPILS_TO_GRADUATE}`,
  },
  CLUB: {
    DETAIL: `${prefixEndpoint}/${END_POINT.CLUB.DETAIL}`,
    ASSIGNED_CLUB: `${prefixEndpoint}/${END_POINT.CLUB.ASSIGNED_CLUB}`,
    ENROLLED_CLUB: `${prefixEndpoint}/${END_POINT.CLUB.ENROLLED_CLUB}`,
    GET_BY_SEMESTER_ACTIVE: `${prefixEndpoint}/${END_POINT.CLUB.GET_BY_SEMESTER_ACTIVE}`,
    GET_ALL:  `${prefixEndpoint}/${PREFIX_CLUB}/${END_POINT.CLUB.GET_ALL}`,
    MAIN_DETAIL: `${prefixEndpoint}/${PREFIX_CLUB}/${END_POINT.CLUB.MAIN_DETAIL}`,
    CREATE: `${prefixEndpoint}/${PREFIX_CLUB}/${END_POINT.CLUB.CREATE}`,
    UPDATE: `${prefixEndpoint}/${PREFIX_CLUB}/${END_POINT.CLUB.UPDATE}`,
    DELETE: `${prefixEndpoint}/${PREFIX_CLUB}/${END_POINT.CLUB.DELETE}`,
  },
  BUS_STOP: {
    INDEX: `${prefixEndpoint}/${PREFIX_BUS_STOP}/${END_POINT.BUS_STOP.INDEX}`,
    DETAIL:  `${prefixEndpoint}/${PREFIX_BUS_STOP}/${END_POINT.BUS_STOP.DETAIL}`,
    CREATE: `${prefixEndpoint}/${PREFIX_BUS_STOP}/${END_POINT.BUS_STOP.CREATE}`,
    UPDATE:  `${prefixEndpoint}/${PREFIX_BUS_STOP}/${END_POINT.BUS_STOP.UPDATE}`,
    DELETE: `${prefixEndpoint}/${PREFIX_BUS_STOP}/${END_POINT.BUS_STOP.DELETE}`,
  },
  INVOICE_MANAGER: {
    INDEX: `${prefixEndpoint}/${PREFIX_INVOICE}/${END_POINT.INVOICE_MANAGER.INDEX}`,
    DETAIL: (id: number) => `${prefixEndpoint}/${PREFIX_INVOICE}/${END_POINT.INVOICE_MANAGER.DETAIL}/${id}`,
    CREATE: `${prefixEndpoint}/${PREFIX_INVOICE}/${END_POINT.INVOICE_MANAGER.CREATE}`,
    EDIT: (id: number) => `${prefixEndpoint}/${PREFIX_INVOICE}/${END_POINT.INVOICE_MANAGER.EDIT}/${id}`,
    DELETE: `${prefixEndpoint}/${PREFIX_INVOICE}/${END_POINT.INVOICE_MANAGER.DELETE}`,
    SCHEDULE: `${prefixEndpoint}/${PREFIX_INVOICE}/${END_POINT.INVOICE_MANAGER.SCHEDULE}`,
    CREATE_PAYMENT: `${prefixEndpoint}/${PREFIX_INVOICE}/create-payment`,
  },
  SUBSCRIPTION_PLAN: {
    ALL: `${prefixEndpoint}/${PREFIX_SUBSCRIPTION_PLAN}/get-all-subscription`,
  },
  CLASS_APPLICATION: {
    GET_LIST: `${prefixEndpoint}/${END_POINT.CLASS_APPLICATION.GET_LIST}`,
    CATEGORY: `${prefixEndpoint}/${END_POINT.CLASS_APPLICATION.CATEGORY}`,
    RESPONSE: `${prefixEndpoint}/${END_POINT.CLASS_APPLICATION.RESPONSE}`,
    GET_LIST_BY_PUPIL: `${prefixEndpoint}/${END_POINT.CLASS_APPLICATION.GET_LIST_BY_PUPIL}`,
    CREATE: `${prefixEndpoint}/${END_POINT.CLASS_APPLICATION.CREATE}`,
    UPDATE: `${prefixEndpoint}/${END_POINT.CLASS_APPLICATION.UPDATE}`,
    DELETE: `${prefixEndpoint}/${END_POINT.CLASS_APPLICATION.DELETE}`,
  },
  ATTENDANCE: {
    PREPARE: `${prefixEndpoint}/${END_POINT.ATTENDANCE.PREPARE}`,
    CREATE: `${prefixEndpoint}/${END_POINT.ATTENDANCE.CREATE}`,
    GET: `${prefixEndpoint}/${END_POINT.ATTENDANCE.GET}`,
    UPDATE: `${prefixEndpoint}/${END_POINT.ATTENDANCE.UPDATE}`,
    LIST: `${prefixEndpoint}/${END_POINT.ATTENDANCE.LIST}`,
    PUPIL_ATTENDANCE: `${prefixEndpoint}/${END_POINT.ATTENDANCE.PUPIL_ATTENDANCE}`,
  },
  BUS: {
    ASSIGNED_BUS: `${prefixEndpoint}/${END_POINT.BUS.ASSIGNED_BUS}`,
    ENROLLMENT_BUS: `${prefixEndpoint}/${END_POINT.BUS.ENROLLMENT_BUS}`,
    DETAIL_BUS: `${prefixEndpoint}/${END_POINT.BUS.DETAIL_BUS}`,
    PUPIL_ENROLLMENT: `${prefixEndpoint}/${END_POINT.BUS.PUPIL_ENROLLMENT}`,
    PUPIL_BUS_DETAIL: `${prefixEndpoint}/${END_POINT.BUS.PUPIL_BUS_DETAIL}`,
    INDEX: `${prefixEndpoint}/${PREFIX_BUS}/${END_POINT.BUS.INDEX}`,
    INFORMATION:  `${prefixEndpoint}/${PREFIX_BUS}/${END_POINT.BUS.INFORMATION}`,
    CREATE: `${prefixEndpoint}/${PREFIX_BUS}/${END_POINT.BUS.CREATE}`,
    UPDATE:  `${prefixEndpoint}/${PREFIX_BUS}/${END_POINT.BUS.UPDATE}`,
    DELETE: `${prefixEndpoint}/${PREFIX_BUS}/${END_POINT.BUS.DELETE}`,
  },
  BUS_ENROLLMENT: {
    INDEX: `${prefixEndpoint}/${PREFIX_BUS_ENROLLMENT}/${END_POINT.BUS_ENROLLMENT.INDEX}`,
    DETAIL:  `${prefixEndpoint}/${PREFIX_BUS_ENROLLMENT}/${END_POINT.BUS_ENROLLMENT.DETAIL}`,
    CREATE: `${prefixEndpoint}/${PREFIX_BUS_ENROLLMENT}/${END_POINT.BUS_ENROLLMENT.CREATE}`,
    UPDATE:  `${prefixEndpoint}/${PREFIX_BUS_ENROLLMENT}/${END_POINT.BUS_ENROLLMENT.UPDATE}`,
    DELETE: `${prefixEndpoint}/${PREFIX_BUS_ENROLLMENT}/${END_POINT.BUS_ENROLLMENT.DELETE}`,
    GET_PUPILS_WITHOUT_BUS: `${prefixEndpoint}/${PREFIX_BUS_ENROLLMENT}/${END_POINT.BUS_ENROLLMENT.GET_PUPILS_WITHOUT_BUS}`,
    GET_BUS_SUPERVISOR_WITHOUT_BUS: `${prefixEndpoint}/${PREFIX_BUS_ENROLLMENT}/${END_POINT.BUS_ENROLLMENT.GET_BUS_SUPERVISOR_WITHOUT_BUS}`,
    GET_PUPILS_IN_BUS_STOP: `${prefixEndpoint}/${PREFIX_BUS_ENROLLMENT}/${END_POINT.BUS_ENROLLMENT.GET_PUPILS_IN_BUS_STOP}`,
  },
  SUBSCRIPTION: {
    ALL: `${prefixEndpoint}/${PREFIX_SUBSCRIPTION_PLAN}/${END_POINT.SUBSCRIPTION.ALL}`,
    DETAIL: `${prefixEndpoint}/${PREFIX_SUBSCRIPTION_PLAN}/${END_POINT.SUBSCRIPTION.DETAIL}`,
  },
  INVOICE: {
    ALL: `${prefixEndpoint}/${PREFIX_SCHOOL_INVOICE}/${END_POINT.INVOICE.ALL}`,
    DETAIL: (id: number) => `${prefixEndpoint}/${PREFIX_SCHOOL_INVOICE}/${END_POINT.INVOICE.DETAIL}/${id}`,
    DELETE: `${prefixEndpoint}/${PREFIX_SCHOOL_INVOICE}/${END_POINT.INVOICE.DELETE}`,
    GET_BY_SUBSCRIPTION: `${prefixEndpoint}/${PREFIX_SCHOOL_INVOICE}/${END_POINT.INVOICE.GET_BY_SUBSCRIPTION}`,
  },
  CLUB_ENROLLMENT: {
    PUPIL_CREATE: `${prefixEndpoint}/${END_POINT.CLUB_ENROLLMENT.PUPIL_CREATE}`,
    UPDATE: `${prefixEndpoint}/${END_POINT.CLUB_ENROLLMENT.UPDATE}`,
    GET_BY_PUPIL_ID: `${prefixEndpoint}/${END_POINT.CLUB_ENROLLMENT.GET_BY_PUPIL_ID}`,
    GET_BY_SEMESTER: `${prefixEndpoint}/${PREFIX_CLUB_ENROLLMENT}/${END_POINT.CLUB_ENROLLMENT.GET_BY_SEMESTER}`,
    CREATE: `${prefixEndpoint}/${PREFIX_CLUB_ENROLLMENT}/${END_POINT.CLUB_ENROLLMENT.CREATE}`,
    UPDATE_INFO: `${prefixEndpoint}/${PREFIX_CLUB_ENROLLMENT}/${END_POINT.CLUB_ENROLLMENT.UPDATE_INFO}`,
    REMOVE: `${prefixEndpoint}/${PREFIX_CLUB_ENROLLMENT}/${END_POINT.CLUB_ENROLLMENT.REMOVE}`,
    GET_TEACHER_NOT_IN_CLUB: `${prefixEndpoint}/${PREFIX_CLUB_ENROLLMENT}/${END_POINT.CLUB_ENROLLMENT.GET_TEACHER_NOT_IN_CLUB}`,
    GET_PUPIL_NOT_IN_CLUB: `${prefixEndpoint}/${PREFIX_CLUB_ENROLLMENT}/${END_POINT.CLUB_ENROLLMENT.GET_PUPIL_NOT_IN_CLUB}`,
    GET_PUPIL_REGISTER_CLUB : `${prefixEndpoint}/${PREFIX_CLUB_ENROLLMENT}/${END_POINT.CLUB_ENROLLMENT.GET_PUPIL_REGISTER_CLUB}`,
    GET_MEMBER_TO_COPY: `${prefixEndpoint}/${PREFIX_CLUB_ENROLLMENT}/${END_POINT.CLUB_ENROLLMENT.GET_MEMBER_TO_COPY}`,
  },
  BUS_ROUTE: {
    INDEX: `${prefixEndpoint}/${PREFIX_BUS_ROUTE}/${END_POINT.BUS_ROUTE.INDEX}`,
    ADD: `${prefixEndpoint}/${PREFIX_BUS_ROUTE}/${END_POINT.BUS_ROUTE.ADD}`,
    UPDATE: `${prefixEndpoint}/${PREFIX_BUS_ROUTE}/${END_POINT.BUS_ROUTE.UPDATE}`,
    DETAIL: `${prefixEndpoint}/${PREFIX_BUS_ROUTE}/${END_POINT.BUS_ROUTE.DETAIL}`,
    DELETE: `${prefixEndpoint}/${PREFIX_BUS_ROUTE}/${END_POINT.BUS_ROUTE.DELETE}`,
  },
  SCORE: {
    CLASS_SCORE_LIST: `${prefixEndpoint}/${END_POINT.SCORE.CLASS_SCORE_LIST}`,
    GET_PUPIL_FOR_CREATE: `${prefixEndpoint}/${END_POINT.SCORE.GET_PUPIL_FOR_CREATE}`,
    CREATE: `${prefixEndpoint}/${END_POINT.SCORE.CREATE}`,
    UPDATE: `${prefixEndpoint}/${END_POINT.SCORE.UPDATE}`,
    GET_PUPIL_SCORE: `${prefixEndpoint}/${END_POINT.SCORE.GET_PUPIL_SCORE}`,
    GET_INDIVIDUAL_SCORE: `${prefixEndpoint}/${END_POINT.SCORE.GET_INDIVIDUAL_SCORE}`,
  },
  SERVICE_PACKAGE: {
    INDEX: `${prefixEndpoint}/${PREFIX_SERVICE_PACKAGE}/${END_POINT.SERVICE_PACKAGE.INDEX}`,
    DETAIL: (id: number) => `${prefixEndpoint}/${PREFIX_SERVICE_PACKAGE}/${END_POINT.SERVICE_PACKAGE.DETAIL}/${id}`,
    UPDATE: (id: number) => `${prefixEndpoint}/${PREFIX_SERVICE_PACKAGE}/${END_POINT.SERVICE_PACKAGE.UPDATE}/${id}`,
    CREATE: `${prefixEndpoint}/${PREFIX_SERVICE_PACKAGE}/${END_POINT.SERVICE_PACKAGE.CREATE}`,
  },
  SCHOOL_YEAR: {
    INDEX: `${prefixEndpoint}/${PREFIX_SCHOOL_YEAR}/${END_POINT.SCHOOL_YEAR.INDEX}`,
    DETAIL: (id: number) => `${prefixEndpoint}/${PREFIX_SCHOOL_YEAR}/${id}/${END_POINT.SCHOOL_YEAR.DETAIL}`,
    CREATE: `${prefixEndpoint}/${PREFIX_SCHOOL_YEAR}/${END_POINT.SCHOOL_YEAR.CREATE}`,
    EDIT: `${prefixEndpoint}/${PREFIX_SCHOOL_YEAR}/${END_POINT.SCHOOL_YEAR.EDIT}`,
    DELETE: (id: number) => `${prefixEndpoint}/${PREFIX_SCHOOL_YEAR}/${id}/${END_POINT.SCHOOL_YEAR.DELETE}`,
  },
  FEEDBACK: {
    CLASS_FEEDBACKS: `${prefixEndpoint}/${END_POINT.FEEDBACK.CLASS_FEEDBACKS}`,
    CREATE_FEEDBACK: `${prefixEndpoint}/${END_POINT.FEEDBACK.CREATE_FEEDBACK}`,
    UPDATE_FEEDBACK: `${prefixEndpoint}/${END_POINT.FEEDBACK.UPDATE_FEEDBACK}`,
    DELETE_FEEDBACK: `${prefixEndpoint}/${END_POINT.FEEDBACK.DELETE_FEEDBACK}`,
    GET_PUPIL_FEEDBACK: `${prefixEndpoint}/${END_POINT.FEEDBACK.GET_PUPIL_FEEDBACK}`,
  },
  DASHBOARD: {
    INDEX: `${prefixEndpoint}/${PREFIX_DASHBOARD}/${END_POINT.DASHBOARD_ADMIN.INDEX}`,
    TOTAL_SCHOOL: `${prefixEndpoint}/${PREFIX_DASHBOARD}/${END_POINT.DASHBOARD_ADMIN.TOTAL_SCHOOL}`,
    TOTAL_SCHOOL_SUBSCRIPTION: `${prefixEndpoint}/${PREFIX_DASHBOARD}/${END_POINT.DASHBOARD_ADMIN.TOTAL_SCHOOL_SUBSCRIPTION}`,
  },
  BUS_SUPERVISOR: {
    GET: `${prefixEndpoint}/${PREFIX_BUS_SUPERVISOR}/${END_POINT.BUS_SUPERVISOR.GET}`,
    UPDATE: `${prefixEndpoint}/${PREFIX_BUS_SUPERVISOR}/${END_POINT.BUS_SUPERVISOR.UPDATE}`,
    CREATE: `${prefixEndpoint}/${PREFIX_BUS_SUPERVISOR}/${END_POINT.BUS_SUPERVISOR.CREATE}`,
    UPDATE_ACCOUNT: `${prefixEndpoint}/${PREFIX_BUS_SUPERVISOR}/${END_POINT.BUS_SUPERVISOR.UPDATE_ACCOUNT}`,
    ALL: `${prefixEndpoint}/${PREFIX_BUS_SUPERVISOR}/${END_POINT.BUS_SUPERVISOR.ALL}`,
    DETAIL: `${prefixEndpoint}/${PREFIX_BUS_SUPERVISOR}/${END_POINT.BUS_SUPERVISOR.DETAIL}`,
    DELETE: `${prefixEndpoint}/${PREFIX_BUS_SUPERVISOR}/${END_POINT.BUS_SUPERVISOR.DELETE}`,
    IMPORT_EXCEL: `${prefixEndpoint}/${PREFIX_BUS_SUPERVISOR}/${END_POINT.BUS_SUPERVISOR.IMPORT_EXCEL}`,
  },
};