const PREFIX_ADMIN = 'admin';
const PREFIX_SCHOOL_ADMIN = 'school';
const PREFIX_PUPIL = 'pupil';
const PREFIX_TEACHER = 'teacher';
const PREFIX_SUPERVISOR = 'supervisor';
export const ROUTER_PATHS = {
  ADMIN: {
    INDEX: `/${PREFIX_ADMIN}/index`,
    INVOICE: `/${PREFIX_ADMIN}/invoice/index`,
    INVOICE_DETAIL: `/${PREFIX_ADMIN}/invoice/detail/:id`,
    DASHBOARD: `/${PREFIX_ADMIN}/dashboard/index`,
    PACKAGE: `/${PREFIX_ADMIN}/service-package/index`,
    SCHOOL: `/${PREFIX_ADMIN}/school-account`,
  },
  SCHOOL_ADMIN: {
    INDEX: `/${PREFIX_SCHOOL_ADMIN}/dashboard`,
    PUPIL_ACCOUNT: `/${PREFIX_SCHOOL_ADMIN}/account/pupil`,
    TEACHER_ACCOUNT: `/${PREFIX_SCHOOL_ADMIN}/account/teacher`,
    SUBSCRIPTION_MANAGER: `/${PREFIX_SCHOOL_ADMIN}/subscription/manager`,
    INVOICE_MANAGER: `/${PREFIX_SCHOOL_ADMIN}/invoice/list`,
    SCHOOLYEAR_MANAGER: `/${PREFIX_SCHOOL_ADMIN}/school-year`,
    INVOICE_DETAIL: `/${PREFIX_SCHOOL_ADMIN}/invoice/detail/:id`,
    ORDER_CHECKOUT: `/${PREFIX_SCHOOL_ADMIN}/subscription/order-checkout`,
    CLASS_MANAGER: `/${PREFIX_SCHOOL_ADMIN}/manage-class`,
    SUBJECT_MANAGE: `/${PREFIX_SCHOOL_ADMIN}/subject/index`,
    SEMESTER_OF_SCHOOLYEAR: `/${PREFIX_SCHOOL_ADMIN}/semester/`,
    CLUB_MANAGEMENT: `/${PREFIX_SCHOOL_ADMIN}/club-management`,
    CLUB_DETAIL: `/${PREFIX_SCHOOL_ADMIN}/club-detail`,
    CLASS_MANAGEMENT: `/${PREFIX_SCHOOL_ADMIN}/manage-class`,
    CLASS_DETAIL: `/${PREFIX_SCHOOL_ADMIN}/class-detail`,
    BUS_SUPERVISOR: `/${PREFIX_SCHOOL_ADMIN}/account/bus-supervisor`,
    TIME_SLOT: `/${PREFIX_SCHOOL_ADMIN}/manage-time-slot`,
    CHANGE_PASSWORD: `/${PREFIX_SCHOOL_ADMIN}/change-password`,
  },
  PUPIL: {
    INDEX: `/${PREFIX_PUPIL}/index`,
    APPLICATION: `/${PREFIX_PUPIL}/application`,
    ATTENDANCE: `/${PREFIX_PUPIL}/attendance`,
    SCORE: `/${PREFIX_PUPIL}/score`,
    FEEDBACK: `/${PREFIX_PUPIL}/feedback`,
    NOTIFICATIONS: `/${PREFIX_PUPIL}/view-notifications`,
    TIMETABLE: `/${PREFIX_PUPIL}/timetable`,
    CLASS_DETAIL: `/${PREFIX_PUPIL}/class-detail`,
    CLUB_DETAIL: `/${PREFIX_PUPIL}/club-detail`,
    BUS_DETAIL: `/${PREFIX_PUPIL}/bus-detail`,
    REGISTER_CLUB: `/${PREFIX_PUPIL}/register-club`,
    HISTORY_REGISTER_CLUB: `/${PREFIX_PUPIL}/history-register-club`,
    PROFILE: `/${PREFIX_PUPIL}/profile`,
    MY_CLASS: `/${PREFIX_PUPIL}/my-class`,
    MY_BUS: `/${PREFIX_PUPIL}/my-bus`,
    CHANGE_PASSWORD: `/${PREFIX_PUPIL}/change-password`,
  },
  TEACHER: {
    INDEX: `/${PREFIX_TEACHER}/index`,
    TIME_TABLE: `/${PREFIX_TEACHER}/Time-Table`,
    CLASS_DETAIL: `/${PREFIX_TEACHER}/Class-Detail`,
    CLASS_APPLICATION: `/${PREFIX_TEACHER}/Class-Application`,
    NOTIFICATIONS_MANAGEMENT: `/${PREFIX_TEACHER}/Notifications-Management`,
    CLUB_DETAIL: `/${PREFIX_TEACHER}/Club-Detail`,
    ATTENDANCE: `/${PREFIX_TEACHER}/Class-Attendance`,
    FEEDBACK: `/${PREFIX_TEACHER}/Feedback-Management`,
    SCORE: `/${PREFIX_TEACHER}/Score-Management`,
    PROFILE: `/${PREFIX_TEACHER}/profile`,
    CHANGE_PASSWORD: `/${PREFIX_TEACHER}/change-password`,
  },
  SUPERVISOR: {
    INDEX: `/${PREFIX_SUPERVISOR}/index`,
    BUS_DETAIL: `/${PREFIX_SUPERVISOR}/Bus-Detail`,
    BUS_ATTENDANCE: `/${PREFIX_SUPERVISOR}/Bus-Attendance`,
    PROFILE: `/${PREFIX_SUPERVISOR}/profile`,
    CHANGE_PASSWORD: `/${PREFIX_SUPERVISOR}/change-password`,
  },
  BUS_ROUTE: {
    INDEX: `/${PREFIX_SCHOOL_ADMIN}/route-management`,
    BUS_ROUTE_DETAIL: `/${PREFIX_SCHOOL_ADMIN}/bus-route-detail`,
  },

  ROOT: '/',
  LOGIN: '/authen/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  USERS: '/users',
  USER: '/users/:id',
  NOT_FOUND: '/404',
  ERROR: '/error',
  SERVER_ERROR: '/500',
  FORBIDDEN: '/403',
  UNAUTHORIZED: '/401',
  BAD_REQUEST: '/400',
  UNPROCESSABLE_ENTITY: '/422',
  LOGOUT: '/logout',
  RESET_PASSWORD: '/reset-password',
  RESET_PASSWORD_TOKEN: '/reset-password/:token',
  CHANGE_PASSWORD: '/change-password',
  CHANGE_PASSWORD_TOKEN: '/change-password/:token',
  VERIFY_EMAIL: '/verify-email',
  VERIFY_EMAIL_TOKEN: '/verify-email/:token',
  VERIFY_PHONE: '/verify-phone',
  VERIFY_PHONE_TOKEN: '/verify-phone/:token',
  VERIFY_PHONE_CODE: '/verify-phone/:token/code',
  VERIFY_PHONE_CODE_TOKEN: '/verify-phone/:token/code/:code',
  VERIFY_PHONE_RESEND: '/verify-phone/:token/resend',
  VERIFY_PHONE_RESEND_TOKEN: '/verify-phone/:token/resend/:code',
  VERIFY_PHONE_RESEND_CODE: '/verify-phone/:token/resend/:code',
  VERIFY_PHONE_RESEND_CODE_TOKEN: '/verify-phone/:token/resend/:code/:newCode',
  VERIFY_PHONE_RESEND_CODE_NEW_TOKEN: '/verify-phone/:token/resend/:code/:newCode',
  VERIFY_PHONE_RESEND_CODE_NEW: '/verify-phone/:token/resend/:code/:newCode',
  VERIFY_PHONE_RESEND_NEW: '/verify-phone/:token/resend/:newCode',
  VERIFY_PHONE_RESEND_NEW_TOKEN: '/verify-phone/:token/resend/:newCode',
  VERIFY_PHONE_RESEND_NEW_CODE: '/verify-phone/:token/resend/:newCode',
  VERIFY_PHONE_RESEND_NEW_CODE_TOKEN: '/verify-phone/:token/resend/:newCode/:newCode',
  VERIFY_PHONE_RESEND_NEW_CODE_NEW_TOKEN: '/verify-phone/:token/resend/:newCode/:newCode',
  VERIFY_PHONE_RESEND_NEW_CODE_NEW: '/verify-phone/:token/resend/:newCode/:newCode',
};
